# Crear una Acción
POST gomarket-production.up.railway.app/acciones
Content-Type: application/json

{
  "simbolo": "AAPL",
  "precio_inicial": 150.00
}

###

# Crear una Orden de Compra
POST gomarket-production.up.railway.app/ordenes
Content-Type: application/json

{
  "usuario_id": 1,
  "tipo": "compra",
  "simbolo": "AAPL",
  "cantidad": 5,
  "precio_limite": 152.00
}

###

# Crear una Orden de Venta
POST gomarket-production.up.railway.app/ordenes
Content-Type: application/json

{
  "usuario_id": 2,
  "tipo": "venta",
  "simbolo": "AAPL",
  "cantidad": 5,
  "precio_limite": 150.00
}

###

# Obtener el Libro de Órdenes
GET gomarket-production.up.railway.app/ordenes?simbolo=AAPL

###

# Obtener el Precio de una Acción
GET gomarket-production.up.railway.app/acciones/AAPL